### ISSUE TITLE
cant finish load mission

### ISSUE THREAD

**Issue by topden** [Quailsnap/WHA-Earplugs-Addon#1]
This mod blocks the start of the mission on the client on a dedicated server. player whist "perpetual download". windows server. without fashion everything is fine.

**Comment by Quailsnap** [comment]
Wait. People other than COALITION have tried using this?
Astounding. Well, this repo isn't really _maintained_, per se, but if you find anything hinting one towards why this would cause clients to hang on load, I can fix it anyways.

**Comment by topden** [comment]
what is "coalition"?

**Comment by Quailsnap** [comment]
coalitiongroup.net is just the unit I made this for, and they threw it in their modpack (a year ago?)

**Comment by topden** [comment]
I do not know what it is or who. In any case, I downloaded your mod now from this site and can not download on any server in any mission (vanilla). I have three dedicated servers with different missions (domination, koth, liberation)

**Comment by topden** [comment]
use without ace3 but cba only. In MP eden all work, but dedic -not . not error on rpt in server and client((

**Comment by Quailsnap** [comment]
How did you find this repo, anyways?
... and try the script version (run a mission with the script in it) https://github.com/Quailsnap/WHA-Earplugs

If it works in local mp but not dedicated it could just be a mod key issue.

**Comment by topden** [comment]
http://joxi.ru/LmGn9RMiwJE4Gr
i start server without bekeys for test

**Comment by Quailsnap** [comment]
So the problem might be (and I forgot because I haven't touched this in a year) the mod isn't setup or signed, and there's a script file in the /tools folder that builds it for you. Did you build it, or did you try to use... this repo, somehow, by just cloning it and slapping it in?

edit: you can't even build it, lmao. the DSKeytool isn't there
I should remove this repo tbqh

**Comment by Quailsnap** [comment]
.. also, how did you find the Earplugs Script version in the first place? 👀

**Comment by topden** [comment]
im not use "tools" folder. only wha_earplugs.pbo
I will use your WHA_nicknames script above the player. and also waited can you make it a mod. you have comfortable work for the game)

**Comment by Quailsnap** [comment]
folk arps has been using the nametag script and coalition has been using a haphazard addon version of the earplug script, but wow! you're the first to actually, like, find these without me showing them to you

so awesome

and because of that I'll give you a built and signed version of this, give me a minute

**Comment by topden** [comment]
demo mission (script version) work on dedic. but i want to mod)))

I edit a lot of missions for my community and I'm tired of inserting scripts every time, which are very helpful in playing all the missions. we have mod builds and I wanted to add your work as a mod so that they work on all missions and always) I'm tired of editing 100+ missions))

**Comment by Quailsnap** [comment]
That's fine and completely understandable. I will build this one for you, but it's actually not-too-hard to make an addon version of a script for yourself that just runs the script at the start of every mission.

Getting permission from script authors to republish their work as a mod is the hard part -- you have full permission from me to adapt any and all scripts I've made into a mod.

**Comment by topden** [comment]
I can sign the mod myself. The problem does not include. the problem is that after downloading from the lobby the player does not get to the briefing (map). loading hangs.

I do not publish the mission. I just rule them for my players to make it easier to play. There are many scripts, but I want everything to be necessary in them. that's how your script with nicknames. we play for ourselves and pleasure, not for advertising)

**Comment by Quailsnap** [comment]
oh I have no idea, then. anything in the rpt?

**Comment by topden** [comment]
nothing....

**Comment by Quailsnap** [comment]
yikes! I wouldn't count on me debugging it,then, I'm afraid. This repo is dead, and I've got a lot of balls in the air right now. If the script version works fine, I would try to take that and shove it into a signed mod.

**Comment by topden** [comment]
it turns out so. The mission begins to work on a server, but the client hangs with a boot screen that does not turn off. T e client is not initialized for some reason. or it "waits" for something. but this wait is endless
http://joxi.ru/Vm64Zwoi4jJ41A

**Comment by topden** [comment]
OK. I'll try ... although I'm a noob, but ...))
I'll write it off if I find the problem and can fix it

**Comment by topden** [comment]
I changed the script in mod. the same trouble does not load. Something with the launch of preinit or postinit...

**Comment by topden** [comment]
http://joxi.ru/bmoJENgH39Kejr I deleted these lines and everything works.
